spring.application.name=SCM
server.port=8081

# mysql database configuration
#data source url



spring.datasource.url=jdbc:mysql://localhost:3306/scm
spring.datasource.username=root
spring.datasource.password=Vinit@123


#jpa configuration
spring.jpa.show-sql=true


#for creating schemas and tables
spring.jpa.hibernate.ddl-auto=update

#security configuration
# spring.security.user.name=ayushmaan
# spring.security.user.password=ayushmaan123

# configuring oauth 2 client
#google properties
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=email,profile



# github configurations 

spring.security.oauth2.client.registration.github.client-id= 
spring.security.oauth2.client.registration.github.client-secret=
spring.security.oauth2.client.registration.github.scope=email,profile